config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  root to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, format: {with: /\A[A-Z]+[a-zA-Z]*\s+[a-zA-Z]{2,}+[.]\z/, message: "wrong format of name"}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :author, presence: true, format: { with: /\A[A-Z]+[a-zA-Z]*\s+[A-Z]+[a-zA-Z]+[.]\z/, message: "wrong format of name" }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category

  mount_uploader :file, FileUploader

  validates :name, presence: true, format: {with: /\A[A-Z]+[a-zA-Z]*\s+[a-zA-Z]{2,}+[.]\z/, message: "wrong format of name"}
  validates :file, file_size: {less_than: 2.megabytes}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to category_path(@post.category)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @category = Category.find(params[:category_id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.create(post_params)
    redirect_to category_path(@category)
  end

  def update
    @post = Post.find(params[:id])

    puts post_params.inspect
    if @post.update(post_params)
      redirect_to category_path(@post.category)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @category = @post.category
    @post.destroy

    redirect_to category_path(@category)
  end

  private
  def post_params
    params.require(:post).permit(:name, :content, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<%= link_to 'Add new', new_category_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category_path(category) %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category_path(category), method: :delete %></td>
      </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<%= form_with scope: :category, url: categories_path, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/categories/show.html.erb
<p>
  <strong>Name :</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description :</strong>
  <%= @category.description %>
</p>

<%= link_to 'Add new post', new_category_post_path(@category) %>

<h2>Posts</h2>
<% @category.posts.each do |post| %>
    <p>
      <strong>Name:</strong>
      <%= post.name %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= post.content %>
    </p>

    <% post.comments.each_with_index do |comment, idx| %>
        <div style="margin-left: <%= 50*idx%>px">
          <p>
            <strong>Name:</strong>
            <%= comment.author %>
          </p>

          <p>
            <strong>Content:</strong>
            <%= comment.content %>
          </p>
        </div>
    <% end %>

    <div>
      <h3>Add a comment:</h3>
      <%= form_with(model: [ post, post.comments.build ], remote: true) do |form| %>
          <p>
            <%= form.label :author %><br>
            <%= form.text_field :author %>
          </p>
          <p>
            <%= form.label :content %><br>
            <%= form.text_area :content %>
          </p>
          <p>
            <%= form.submit %>
          </p>
      <% end %>
      <div><%= link_to 'Edit', edit_post_path(post) %></div>
      <div><%= link_to 'Destroy', post_path(post), method: :delete %></div>
    </div>

<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit a post:</h2>
<%= form_with(model: @post, local: true, :html => {multipart: true}) do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </p>
    <p>
      <%= form.label :file %><br>
      <%= form.file_field @post.file %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/posts/new.html.erb
<h2>Add a post:</h2>
<%= form_with(model: [ @category, @category.posts.build ], local: true, :html => {multipart: true}) do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </p>
    <p>
      <%= form.label :file %><br>
      <%= form.file_field :file %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>